name: Infra-automation-health-check to Sheets

on:
  schedule:
    - cron: '50 23 * * *' # Run at 23:50 UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
    update-sheets:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: 3.9

            - name: Install dependencies
              run: |
                    cd infra-automation-health-check
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Setup Google Service Account
              run: |
                echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}' | base64 -d > service_account.json
            
            - name: Run uptime check and update sheets
              run: |
                    cd infra-automation-health-check
                    python main.py
              env:
                    GOOGLE_APPLICATION_CREDENTIALS: ../service_account.json
                    FINCRA_GITHUB_TOKEN: ${{ secrets.FINCRA_GITHUB_TOKEN }}
